testPronia/Models/Tag.cs
using System.ComponentModel.DataAnnotations;

namespace testPronia.Models
{
    public class Tag
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(25)]
        public string Name { get; set; }
        public List<ProductTag>? ProductTags { get; set; }
    }
}

testPronia/Areas/ProniaAdmin/Controllers/TagController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using testPronia.Areas.ViewModels;
using testPronia.DAL;
using testPronia.Models;

namespace testPronia.Areas.ProniaAdmin.Controllers
{
	[Area("ProniaAdmin")]
	public class TagController : Controller
	{
		private readonly AppDbContext _context;

		public TagController(AppDbContext context)
        {
			_context = context;
        }
        public async Task<IActionResult> Index(int page)
		{
			double count = await _context.Tags.CountAsync();
			if (page < 0)
			{
				return BadRequest();
			}
			else if (page > Math.Ceiling(count / 3))
			{
				return NotFound();
			}
			List<Tag> tags = await _context.Tags.Skip(page*3).Take(3).Include(t => t.ProductTags).ToListAsync();
			PaginateVM<Tag> paginateVM = new PaginateVM<Tag>()
			{
				CurrentPage = page+1,
				TotalPage = Math.Ceiling(count/3),
				Items = tags
			};
			return View(paginateVM);
		}
		[Authorize(Roles = "Admin,Moderator")]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Create(Tag tag)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}
			
			bool result = _context.Tags.Any(c => c.Name.ToLower().Trim() == tag.Name.ToLower().Trim());
			if (result)
			{
				ModelState.AddModelError("Name", "Tag already exists");
				return View();
			}

			await _context.Tags.AddAsync(tag);
			await _context.SaveChangesAsync();

			return RedirectToAction("Index");
		}
		[Authorize(Roles = "Admin,Moderator")]
		public async Task<IActionResult> Update(int id)
		{
			if (id <= 0) return BadRequest();
			Tag tag = await _context.Tags.FirstOrDefaultAsync(t => t.Id == id);
			return View(tag);
		}

		[HttpPost]
		public async Task<IActionResult> Update(int id, Tag tag)
		{
			if (!ModelState.IsValid) { return View(); }

			Tag existed = await _context.Tags.FirstOrDefaultAsync(t => t.Id == id);

			if (existed == null) return NotFound();

			bool result = _context.Tags.Any(t => t.Name == tag.Name && t.Id == id);
			if (result) { ModelState.AddModelError("Name", "Tag already exists"); return View(); }

			existed.Name = tag.Name;

			_context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));

		}
		[Authorize(Roles = "Admin")]
		async public Task<IActionResult> Delete(int id)
		{
			if (id <= 0) return BadRequest();
			Tag existed = await _context.Tags.FirstOrDefaultAsync(t => t.Id == id);

			_context.Tags.Remove(existed);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));




		}
		[Authorize(Roles = "Admin,Moderator")]
		public async Task<IActionResult> Details(int id)
        {

			List<ProductTag> productTags = await _context.ProductTags.Include(pt => pt.Product.ProductImages).Where(t => t.TagId == id).ToListAsync();
			
            
            return View(productTags);
        }


    }
}

testPronia/Areas/ProniaAdmin/Views/Tag/Create.cshtml
@model Tag
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Create Tag</h4>

                        <form class="forms-sample" method="post">

                            <div class="form-group">
                                <label asp-for="Name">Name</label>
                                <input asp-for="Name" class="form-control" placeholder="Name">
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>

                            <button type="submit" class="btn btn-primary me-2">Submit</button>
                            <button class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

testPronia/Areas/ProniaAdmin/Views/Tag/Details.cshtml
@model List<ProductTag>
<div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach (ProductTag productTag in Model)
    {
        <div class="col">
            <div class="card">
                <img src="~/assets/images/website-images/@productTag.Product.ProductImages.FirstOrDefault(pi=>pi.IsPrimary==true)?.Url" class="card-img-top" alt="@productTag.Product.Name">
                <div class="card-body">
                    <h5 class="card-title">Name: @productTag.Product.Name</h5>
                    <p class="card-text">Price: @productTag.Product.Price</p>
                </div>
            </div>
        </div>
    }
</div>

testPronia/Areas/ProniaAdmin/Views/Tag/Index.cshtml
@model PaginateVM<Tag>
@{
	int count = (Model.CurrentPage-1)*3;
}
<div class="main-panel">
	<div class="content-wrapper">
		<div class="row">
			<div class="col-lg-12 grid-margin stretch-card">
				<div class="card">
					<div class="card-body">
						<h4 class="card-title">Tag Table</h4>
						<a asp-controller="Tag" asp-action="Create" class="btn btn-success">Create Tag</a>
						<div class="table-responsive">
							<table class="table table-striped">
								<thead>
									<tr>
										<th>
											No
										</th>
										<th>
											Name
										</th>

										<th>
											Settings
										</th>

									</tr>
								</thead>
								<tbody>
									@foreach (Tag tag in Model.Items)
									{
										count++;
										<tr>
											<td>
												@count
											</td>

											<td>
												@tag.Name
											</td>



											<td>
												<a asp-controller="Tag" asp-action="Update" asp-route-id="@tag.Id" class="btn btn-warning btn-info"><i class="mdi mdi-pencil"></i></a>
												<a asp-controller="Tag" asp-action="Delete" asp-route-id="@tag.Id"	class="btn btn-danger btn-info"><i class="mdi mdi-delete"></i></a>
												<a asp-controller="Tag" asp-action="Details" asp-route-id="@tag.Id" class="btn btn-success"><i class="mdi mdi-open-in-new"></i></a>
											</td>
										</tr>
									}
							</table>
						</div>
						<nav aria-label="Page navigation example">
							<ul class="pagination">
								<li class="page-item @(Model.CurrentPage==1?"disabled":"")"><a class="page-link" asp-controller="Tag" asp-action="Index" asp-route-page="@(Model.CurrentPage-2)">Previous</a></li>
								@for (int i = 1; i < Model.TotalPage; i++)
								{
									<li class="page-item @(i==Model.CurrentPage?"disabled":"")"><a class="page-link" asp-controller="Tag" asp-action="Index" asp-route-page="@(i-1)">@i</a></li>
								}

								<li class="page-item @(Model.CurrentPage==Model.TotalPage?"disabled":"")"><a class="page-link" asp-controller="Tag" asp-action="Index" asp-route-page="@(Model.CurrentPage)">Next</a></li>
							</ul>
						</nav>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

testPronia/Areas/ProniaAdmin/Views/Tag/Update.cshtml
@model Tag
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Update Tag</h4>

                        <form class="forms-sample" method="post">

                            <div class="form-group">
                                <label asp-for="Name">Name</label>
                                <input asp-for="Name" class="form-control" placeholder="Name">
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>

                            <button type="submit" class="btn btn-primary me-2">Submit</button>
                            <button class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>