testPronia/Models/Slide.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace testPronia.Models
{
    public class Slide
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(25)]
        public string Title { get; set; }
        [Required]
        [MaxLength(25)]
        public string SubTitle { get; set; }
        [Required]
        [MaxLength(25)]
        public string Description { get; set; }
        public string? SlideImageUrl { get; set; }
        [Required]
        public int Order { get; set; }
        [NotMapped]
        public IFormFile? Photo { get; set; }
    }
}

testPronia/Areas/ProniaAdmin/Controllers/SlideController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using testPronia.Areas.ViewModels;
using testPronia.DAL;
using testPronia.Models;
using testPronia.Utilities.Extensions;

namespace testPronia.Areas.ProniaAdmin.Controllers
{
	[Area("ProniaAdmin")]
	public class SlideController : Controller
	{
		private readonly AppDbContext _context;
		private readonly IWebHostEnvironment _env;

		

		public SlideController(AppDbContext context, IWebHostEnvironment env)
        {
			_context = context;
			_env = env;
        }
		
        public IActionResult Index()
		{
            List<Slide> slides = _context.Slides.ToList();
			return View(slides);
		}
		[Authorize(Roles = "Admin,Moderator")]
		public IActionResult Create()
		{
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Create(CreateSlideVM slideVM)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}
			if (slideVM.Photo == null)
			{
				ModelState.AddModelError("Photo","Photo required");
				return View();
				
			}

			if (!slideVM.Photo.ValidateType("image/"))
			{
				ModelState.AddModelError("Photo","Incorrect file type");
				return View();
			}

			if(!slideVM.Photo.ValidateSize(2*1024))
			{
				ModelState.AddModelError("Photo", "Photo size should not be larger than 2 mb");
				return View();
				
			}
			if (slideVM.Order <= 0)
			{
				ModelState.AddModelError("Order", "Order cannot be less than 0");
			}
			

		     string fileName = await slideVM.Photo.CreateFile(_env.WebRootPath,"assets","images","slider");
			Slide slide = new Slide
			{
				Title = slideVM.Title,
				SubTitle = slideVM.SubTitle,
				Description = slideVM.Description,
				Order = slideVM.Order,
				SlideImageUrl=fileName
			};

			await _context.AddAsync(slide);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}
		[Authorize(Roles = "Admin,Moderator")]
		public async Task<IActionResult> Details(int id)
		{
			Slide slide= await _context.Slides.FirstOrDefaultAsync(s => s.Id == id);
			return View(slide);
		}
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Delete(int id)
		{
			if (id <= 0)
			{
				return BadRequest();
			}
			Slide slide = await _context.Slides.FirstOrDefaultAsync(s => s.Id == id);
			slide.SlideImageUrl.DeleteFile(_env.WebRootPath, "assets", "images", "slider");
			_context.Slides.Remove(slide);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));

		}
		[Authorize(Roles = "Admin,Moderator")]
		public async Task<IActionResult> Update(int id)
		{
			if (id <= 0) { return BadRequest(); }
			Slide existed = await _context.Slides.FirstOrDefaultAsync(s=> s.Id==id);
			if (existed == null) { return NotFound(); }

			UpdateSlideVM slideVM = new UpdateSlideVM {
			SlideImageUrl = existed.SlideImageUrl,
			Title = existed.Title,
			SubTitle= existed.SubTitle,
			Description = existed.Description,
			Order = existed.Order
			
			
			};
			return View(slideVM);

		}
		[HttpPost]
		public async Task<IActionResult> Update(int id,CreateSlideVM slideVM)
		{
			if (!ModelState.IsValid) { return View(slideVM); }

			Slide existed = await _context.Slides.FirstOrDefaultAsync(c => c.Id == id);

			if (existed == null) return NotFound();

			slideVM.SlideImageUrl = existed.SlideImageUrl;
			slideVM.Title = existed.Title;
			slideVM.SubTitle = existed.SubTitle;
			slideVM.Description = existed.Description;
			slideVM.Order = existed.Order;




			_context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));


		}

	}
}

testPronia/Areas/ProniaAdmin/Views/Slide/Create.cshtml
@model CreateSlideVM
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Create Slide</h4>

                        <form class="forms-sample" method="post" enctype="multipart/form-data">

                            <div class="form-group">
                                <label asp-for="Photo">Photo</label>
                                <input asp-for="Photo"  class="form-control" placeholder="Photo">
                                <span class="text-danger" asp-validation-for="Photo"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Title">Title</label>
                                <input asp-for="Title" class="form-control" placeholder="Title">
                                <span class="text-danger" asp-validation-for="Title"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="SubTitle">Subtitle</label>
                                <input asp-for="SubTitle" class="form-control" placeholder="Subtitle">
                                <span class="text-danger" asp-validation-for="SubTitle"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description">Description</label>
                                <input asp-for="Description" class="form-control" placeholder="Description">
                                <span class="text-danger" asp-validation-for="Description"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Order">Order</label>
                                <input asp-for="Order" class="form-control" placeholder="Order">
                                <span class="text-danger" asp-validation-for="Order"></span>
                            </div>

                            <button type="submit" class="btn btn-primary me-2">Submit</button>
                            <button class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

testPronia/Areas/ProniaAdmin/Views/Slide/Details.cshtml
@model Slide 
    <div class="card">
    <img src="~/assets/images/slider/@Model.SlideImageUrl" class="card-img-top" alt="@Model.Title">
  <div class="card-body">
        <h5 class="card-title">@Model.Title</h5>
        <p class="card-text">@Model.SubTitle</p>
        <p class="card-text">@Model.Description</p>
    
  </div>
</div>
    

testPronia/Areas/ProniaAdmin/Views/Slide/Index.cshtml
@model List<Slide>
@{
	int count = 0;
}
<div class="main-panel">
	<div class="content-wrapper">
		<div class="row">
			<div class="col-lg-12 grid-margin stretch-card">
				<div class="card">
					<div class="card-body">
						<h4 class="card-title">Slide Table</h4>
						<a asp-controller="Slide" asp-action="Create" class="btn btn-success">Create Slide</a>
						<div class="table-responsive">
							<table class="table table-striped">
								<thead>
									<tr>
										<th>
											No
										</th>
										<th>
											Image
										</th>
										<th>
											Title
										</th>
										<th>
											Order
										</th>
										<th>
											Settings
										</th>

									</tr>
								</thead>
								<tbody>
									@foreach (Slide slide in Model)
									{
										count++;
										<tr>
											<td>
												@count
											</td>

											<td>
												<img src="~/assets/images/slider/@slide.SlideImageUrl"/>
											</td>

											<td>
												@slide.Title
											</td>
											<td>
												@slide.Order
											</td>

											<td>
												<a asp-controller="Slide" asp-action="Update" asp-route-id=" @slide.Id" class="btn btn-warning btn-info"><i class="mdi mdi-pencil"></i></a>
												<a asp-controller="Slide" asp-action="Delete" asp-route-id="@slide.Id" class="btn btn-danger btn-info"><i class="mdi mdi-delete"></i></a>
												<a asp-controller="Slide" asp-action="Details" asp-route-id="@slide.Id" class="btn btn-success"><i class="mdi mdi-open-in-new"></i></a>
											</td>
										</tr>
									}
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

testPronia/Areas/ProniaAdmin/Views/Slide/Update.cshtml
@model CreateSlideVM
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Update Slide</h4>

                        <form class="forms-sample" method="post" enctype="multipart/form-data">

                            <div class="form-group">
                                <img src="~/assets//images/slider/@Model.SlideImageUrl"/>
                                <input asp-for="SlideImageUrl" class="form-control" placeholder="Photo">

                            </div>

                            <div class="form-group">
                                <label asp-for="Photo">Photo</label>
                                <input asp-for="Photo" class="form-control" placeholder="Photo">
                                <span class="text-danger" asp-validation-for="Photo"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Title">Title</label>
                                <input asp-for="Title" class="form-control" placeholder="Title">
                                <span class="text-danger" asp-validation-for="Title"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="SubTitle">Subtitle</label>
                                <input asp-for="SubTitle" class="form-control" placeholder="Subtitle">
                                <span class="text-danger" asp-validation-for="SubTitle"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description">Description</label>
                                <input asp-for="Description" class="form-control" placeholder="Description">
                                <span class="text-danger" asp-validation-for="Description"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Order">Order</label>
                                <input asp-for="Order" class="form-control" placeholder="Order">
                                <span class="text-danger" asp-validation-for="Order"></span>
                            </div>

                            <button type="submit" class="btn btn-primary me-2">Submit</button>
                            <button class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>