testPronia/Models/Color.cs
namespace testPronia.Models
{
    public class Color
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<ProductColor>? ProductColors{ get; set; }
    }
}

testPronia/Areas/ProniaAdmin/Controllers/ColorController.cs
using System.Drawing;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using testPronia.DAL;
using testPronia.Models;

namespace testPronia.Areas.ProniaAdmin.Controllers
{
	[Area("ProniaAdmin")]
	public class ColorController : Controller
	{
		private readonly AppDbContext _context;

		public ColorController(AppDbContext context)
        {
            _context= context;
        }
        public IActionResult Index()
		{
			List<Models.Color> colors = _context.Colors.ToList();

			return View(colors);
		}
		[Authorize(Roles = "Admin,Moderator")]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Create(Models.Color color)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}
			bool result = _context.Colors.Any(c => c.Name.ToLower().Trim() == color.Name.ToLower().Trim());
			if (result)
			{
				ModelState.AddModelError("Name", "Color already exists");
				return View();
			}

			await _context.Colors.AddAsync(color);
			await _context.SaveChangesAsync();

			return RedirectToAction(nameof(Index));

		}
		[Authorize(Roles = "Admin")]
		async public Task<IActionResult> Delete(int id)
		{
			if (id <= 0) return BadRequest();
			Models.Color existed = await _context.Colors.FirstOrDefaultAsync(c => c.Id == id);

			_context.Colors.Remove(existed);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));

		}
		[Authorize(Roles = "Admin,Moderator")]
		public async Task<IActionResult> Update(int id)
		{
			if (id <= 0) return BadRequest();
			Models.Color colors = await _context.Colors.FirstOrDefaultAsync(c => c.Id == id);
			return View(colors);
		}

		[HttpPost]
		public async Task<IActionResult> Update(int id, Models.Color color)
		{
			if (!ModelState.IsValid) { return View(); }

			Models.Color existed = await _context.Colors.FirstOrDefaultAsync(c => c.Id == id);

			if (existed == null) return NotFound();

			bool result = _context.Colors.Any(c => c.Name == color.Name && c.Id == id);
			if (result) { ModelState.AddModelError("Name", "Color already exists"); return View(); }

			existed.Name = color.Name;

			_context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));

		}


		[Authorize(Roles = "Admin,Moderator")]
		public async Task<IActionResult> Details(int id)
        {

            List<ProductColor> productColors = await _context.ProductColors.Include(pc => pc.Product.ProductImages).Where(c => c.ColorId == id).ToListAsync();


            return View(productColors);
        }
    }
}

testPronia/Areas/ProniaAdmin/Views/Color/Create.cshtml
@model Color
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Create Color</h4>

                        <form class="forms-sample" method="post">

                            <div class="form-group">
                                <label asp-for="Name">Name</label>
                                <input asp-for="Name" class="form-control" placeholder="Name">
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>

                            <button type="submit" class="btn btn-primary me-2">Submit</button>
                            <button class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

testPronia/Areas/ProniaAdmin/Views/Color/Details.cshtml
@model List<ProductColor>
<div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach (ProductColor productColor in Model)
    {
        <div class="col">
            <div class="card">
                <img src="~/assets/images/website-images/@productColor.Product.ProductImages.FirstOrDefault(pi=>pi.IsPrimary==true)?.Url" class="card-img-top" alt="@productColor.Product.Name">
                <div class="card-body">
                    <h5 class="card-title">Name: @productColor.Product.Name</h5>
                    <p class="card-text">Price: @productColor.Product.Price</p>
                </div>
            </div>
        </div>
    }
</div>

testPronia/Areas/ProniaAdmin/Views/Color/Index.cshtml
@model List<Color>
@{
	int count = 0;
}
<div class="main-panel">
	<div class="content-wrapper">
		<div class="row">
			<div class="col-lg-12 grid-margin stretch-card">
				<div class="card">
					<div class="card-body">
						<h4 class="card-title">Color Table</h4>
						<a asp-controller="Color" asp-action="Create" class="btn btn-success">Create Color</a>
						<div class="table-responsive">
							<table class="table table-striped">
								<thead>
									<tr>
										<th>
											No
										</th>
										<th>
											Name
										</th>
									
										<th>
											Settings
										</th>

									</tr>
								</thead>
								<tbody>
									@foreach (Color color in Model)
									{
										count++;
										<tr>
											<td>
												@count
											</td>

											<td>
												@color.Name
											</td>

										

											<td>
												<a asp-controller="Color" asp-action="Update" asp-route-id="@color.Id" class="btn btn-warning btn-info"><i class="mdi mdi-pencil"></i></a>
												<a asp-controller="Color" asp-action="Delete" asp-route-id="@color.Id" class="btn btn-danger btn-info"><i class="mdi mdi-delete"></i></a>
												<a asp-controller="Color" asp-action="Details" asp-route-id="@color.Id" class="btn btn-success"><i class="mdi mdi-open-in-new"></i></a>
											</td>
										</tr>
									}
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

testPronia/Areas/ProniaAdmin/Views/Color/Update.cshtml
@model Color
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Update Color</h4>

                        <form class="forms-sample" method="post">

                            <div class="form-group">
                                <label asp-for="Name">Name</label>
                                <input asp-for="Name" class="form-control" placeholder="Name">
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>

                            <button type="submit" class="btn btn-primary me-2">Submit</button>
                            <button class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860